#!# perl: poros/code/exec
use strict;
use warnings;
use YAML::XS;

return sub
{
    my (  %param, $i ) = @_;

    map
    {
        printf "exec[%d]: [$_]\n", ++ $i;

        system $_;

        if( $? == -1 )
        {
            print "failed to execute: $!\n";
            return 1;
        }
        elsif ( $? & 127 )
        {
            printf "child died with signal %d, %s coredump\n",
                ( $? & 127 ), ( $? & 128 ) ? 'with' : 'without';
            return 1;
        }

        my $exit = $? >> 8;
        return $exit if $exit && print "child exited with value $exit\n";

    }@{$param{argv}};

    return 0;
};
