#!/home/s/ops/perl/bin/perl

use strict;
use warnings;

use YAML::XS;
use File::Spec;

use NS::Util::ExpSSH;
use NS::Util::OptConf;

$| ++;

$NS::Util::OptConf::ARGC = -1;

=head1 SYNOPSIS

 $0 host [user]

=cut

my %o = NS::Util::OptConf->load()->get()->dump();
my $user = `logname`; chomp $user;
my $pass = $ENV{PASSWD};


unless( $pass )
{
    my $conf = File::Spec->join( ( getpwnam $user )[7], '.go' );
    $conf = eval { YAML::XS::LoadFile $conf };
    $pass = $conf->{$user} if $conf && ref $conf eq 'HASH' && defined $conf->{$user};
}

die "cannot resolve host\n" unless NS::Util::ExpSSH->new()
    ->conn( pass => $pass, user => $user, host => shift, sudo => shift );
