#!/data/scripts/nices/perl/bin/perl
use strict;
use warnings;

use YAML::XS;

use NS::Util::OptConf;
use NS::Util::Merge;

=head1 SYNOPSIS

 $0 file.master file.1 file.2 file.3
    
=cut

my $option = NS::Util::OptConf->load();
my %o = $option->get( qw( check ) )->dump();
$option->assert() if @ARGV < 2;

my $m = NS::Util::Merge->new( file => shift @ARGV );
my $r = $m->merge( @ARGV );

my( $title, $cont, $change ) = @$r{qw( title cont change )};

printf "  %s\n", join "\t", map{ $title->{$_}}0..keys( %{$title} ) -1;
for my $id ( 0 .. @$cont-1 )
{
    printf "%s %s\n", defined $change->{$id} ? '*': ' ', 
        join "\t",  map{ $_ || 'unkown' }@{$cont->[$id]};
}

