#!/data/scripts/nices/perl/bin/perl

=head1 SYNOPSIS

 $0 [--src src-range] --dst dst-range --sp src-path [--dp dst-path] \
    [--timeout seconds] [--max number] [--Retry number] [--nice number] 
    [rsync options] 

=cut
use strict;
use warnings;
use Sys::Hostname;

use NS::Hermes;
use NS::Poros::Mrsync;
use NS::Util::OptConf;

$| ++;

@NS::Util::OptConf::CONF = qw( pass_through no_ignore_case );

my $option = NS::Util::OptConf->load();
my %o = $option->set( retry => 2, timeout => 300, src => hostname() )
    ->get( qw( range=s src=s dst=s sp=s dp=s timeout=i max=i Retry=i nice=i ) )
    ->dump();

$o{dst} ||= $o{range};

my $range = NS::Hermes->new( $option->dump( 'range' ) );
my $mrsync = NS::Poros::Mrsync->new
(
    ( map { $_ => delete $o{$_} } qw( sp dp ) ),
    map { $_ => [ $range->load( delete $o{$_} || [] )->list ] } qw( src dst )
);

$o{opt} = join ' ', @ARGV if @ARGV;

exit 0 unless my @failed = $mrsync->run( %o )->failed();
system 'stty echo';
die $range->load( \@failed )->dump . ": failed.\n\n";
