#!/data/scripts/nices/perl/bin/perl

=head1 SYNOPSIS

 $0 [--port num] [--max num] script

 $0 [--port num] [--max num] --thread script

=cut
use strict;
use warnings;

use NS::Util::TcpServer;
use NS::Util::OptConf;

$NS::Util::OptConf::ARGC = 1;

$| ++;

#@NS::Util::OptConf::CONF = qw( pass_through no_ignore_case );

my $option = NS::Util::OptConf->load();
my %o = $option->set( port => 4000, max => 20 )->get( qw( port=i max=i thread ) )->dump();


NS::Util::TcpServer->new(
    port  => $o{port},
    'exec' => shift
)->run( 
    maxcon => $o{max},
    thread => $o{thread}
);
