#!/home/s/ops/perl/bin/perl
use strict;
use warnings;

use YAML::XS;
use NS::Hermes;

use NS::VSSH;
use NS::VSSH::Auth;
use NS::Util::OptConf;

=head1 SYNOPSIS

 $0 [--range host] [--user user] [--max maxthread] [--timeout num] [--verbose] 
        [--hostdb /my/hostdb/path ]
    
=cut

$NS::Util::OptConf::THIS = 'vssh';

my $option = NS::Util::OptConf->load();
my %o = $option->get( qw( range=s user=s max=i timeout=i hostdb=s verbose ) )->dump();

my $range = NS::Hermes->new( $option->dump( 'range' ) );
 
my $user = $o{user} || `logname`;
chomp $user;

exit 0 unless NS::VSSH::Auth->new( user => $user )->checkpw( 3 );

NS::VSSH->new( 
    timeout => $o{timeout},
    max => $o{max},
    user => $user,
    host => $o{range} ? [ $range->load( delete $o{range} )->list ] : [],
    quiet => $o{verbose} ? 0 : 1,
    hostdb => $o{hostdb},
)->run();
