#!/home/work/nices/perl/bin/perl
use strict;
use warnings;
use NS::Hermes;
use NS::Util::OptConf;

use NS::VSSH;

=head1 SYNOPSIS

 $0 [--range host]
    
=cut

my $option = NS::Util::OptConf->load();
my %o = $option->get( qw( range=s ) )->dump( 'vssh' );
my $range = NS::Hermes->new( $option->dump( 'range' ) );
 
$option->assert( 'range' );

exit unless my @node = $range->load( delete $o{range} )->list;

NS::VSSH->new( node => \@node )->run();
