#!/home/s/ops/perl/bin/perl
use strict;
use warnings;
use NS::Apollo;
use FindBin qw( $RealBin );

my $apollo = NS::Apollo->new( 
    code => "$RealBin/../code",
    conf => "$RealBin/../conf/config"
);

my $interval = defined $ARGV[0] && $ARGV[0] =~ /^\d+$/ ? $ARGV[0] : 900;

print "run...\n";
sleep 5 if $interval;

while( my $time = time )
{
    $apollo->run();
    last unless $interval;
    my $due = $time + $interval - time;
    sleep $due if $due > 0;
}
