#!# perl: apollo/code/foo
use strict;
use warnings;
use Carp;

# task => check  %% jobs for check
# task => apollo %% jobs for apollo

return sub
{
    my ( %param, $stat  ) = @_;

    if( $param{task} eq 'check' )
    {
        #check bala bala ...
        $stat = int rand 4;
    }
    else
    {
        $stat = int rand 2;
    }

    &{$param{say}}( "stat: $stat" );
    return $stat;
};
