#!# perl: argos/code/pool.batch
use strict;
use Carp;

use Data::Dumper;
use NS::Collector::Stat;

return sub
{
    my %param = @_;

    print Dumper \%param;

    my $stat = NS::Collector::Stat->new( test => $param{test} )->eval;
    

    return $stat->stat;
};
